### ISSUE TITLE
add recursive function to get_upstream_replies()

### ISSUE THREAD

**Issue by bretsw** [ropensci/tidytags#17]

**Comment by jrosen48** [comment]
is this addressed already @bretsw?

**Comment by bretsw** [comment]
Not yet addressed. get_upstream_replies() works but an improvement could be made if we implemented your recursive code.

**Comment by jrosen48** [comment]
ah got it. let's hold off until next stage - when we also add a shiny (or data that could easily be used to create one)? does that sound good?

________________________________________

**Comment by bretsw** [comment]
Yes, sounds like a plan. This was my intention, and why I labeled this as an "enhancement." We'll come back to later

**Comment by jrosen48** [comment]
Oops sorry missed that, sounds good
________________________________

**Comment by bretsw** [comment]
Due to changes in the X/Twitter API, we are no longer able to maintain tidytags, and the package has been archived. See https://devdevguide.netlify.app/maintenance_evolution#archivalguidance
